import type { ThemeConfig, ThemeId } from '../types/theme';

export const THEMES: Record<ThemeId, ThemeConfig> = {
  coastal: {
    id: 'coastal',
    name: 'Costa Bruma (Rosarito)',
    tagline: 'Café de especialidad, brisa marina y tostaduría artesanal',
    icon: '🌊',
    badge: 'Rosarito Especial',
    isDark: false,
    previewColors: ['#C86D51', '#2C4A52', '#F9F6F0', '#E3A857'],
    fontFamily: {
      heading: "'Outfit', sans-serif",
      body: "'Plus Jakarta Sans', sans-serif",
    },
    styles: {
      bg: 'bg-[#F6F2EB]',
      bgCard: 'bg-white border-[#D6C7B2]',
      bgCardHover: 'hover:border-[#C86D51] hover:shadow-xl hover:shadow-[#C86D51]/15',
      bgHeader: 'bg-[#F6F2EB]/95 backdrop-blur-md border-[#D6C7B2]',
      textPrimary: 'text-[#1C1612]',
      textSecondary: 'text-[#44382F]',
      textMuted: 'text-[#6E5F53]',
      accent: 'bg-[#C86D51] text-white',
      accentHover: 'hover:bg-[#B35B40]',
      accentText: 'text-[#C86D51]',
      border: 'border-[#D6C7B2]',
      borderAccent: 'border-[#C86D51]',
      badgeBg: 'bg-[#C86D51]/15',
      badgeText: 'text-[#A04A30]',
      radius: 'rounded-2xl',
      shadow: 'shadow-md shadow-[#C86D51]/10',
      buttonStyle: 'rounded-xl shadow-md transition-all active:scale-95 font-extrabold',
      cardStyle: 'border-2 transition-all duration-300 shadow-sm',
    },
  },

  drinko: {
    id: 'drinko',
    name: 'Drinko Studio (Warm Editorial)',
    tagline: 'Diseño editorial cálido, arena de playa, tipografía bold y acentos terracota',
    icon: '🏺',
    badge: 'Warm Editorial',
    isDark: false,
    previewColors: ['#B87A53', '#EAE3D6', '#2A1B14', '#F4B0A1'],
    fontFamily: {
      heading: "'Syne', 'Outfit', sans-serif",
      body: "'Plus Jakarta Sans', sans-serif",
    },
    styles: {
      bg: 'bg-[#EAE3D6]',
      bgCard: 'bg-[#DFD5C4] border-[#C8BAA3]',
      bgCardHover: 'hover:border-[#B87A53] hover:shadow-xl hover:shadow-[#B87A53]/20',
      bgHeader: 'bg-[#EAE3D6]/95 backdrop-blur-md border-[#C8BAA3]',
      textPrimary: 'text-[#2A1B14]',
      textSecondary: 'text-[#543D32]',
      textMuted: 'text-[#7D6456]',
      accent: 'bg-[#B87A53] text-white',
      accentHover: 'hover:bg-[#9E623E]',
      accentText: 'text-[#B87A53]',
      border: 'border-[#C8BAA3]',
      borderAccent: 'border-[#B87A53]',
      badgeBg: 'bg-[#B87A53]/20',
      badgeText: 'text-[#874825]',
      radius: 'rounded-2xl',
      shadow: 'shadow-md shadow-[#B87A53]/10',
      buttonStyle: 'rounded-full px-4 py-2 font-black transition-all active:scale-95 shadow-sm',
      cardStyle: 'border-2 transition-all duration-300 shadow-sm',
    },
  },

  mccafe: {
    id: 'mccafe',
    name: 'McCafé Interactive Showcase',
    tagline: 'Estructura idéntica a la imagen: carrusel interactivo, tarjeta caramelo y personalizador',
    icon: '☕',
    badge: 'McCafé UI',
    isDark: false,
    previewColors: ['#DFB794', '#381F13', '#FFFFFF', '#D9381E'],
    fontFamily: {
      heading: "'Outfit', 'Plus Jakarta Sans', sans-serif",
      body: "'Plus Jakarta Sans', sans-serif",
    },
    styles: {
      bg: 'bg-[#2E180E]',
      bgCard: 'bg-[#F0EFEB] border-[#E2DFD7]',
      bgCardHover: 'hover:border-[#DFB794] hover:shadow-xl',
      bgHeader: 'bg-white border-[#E2DFD7]',
      textPrimary: 'text-[#381F13]',
      textSecondary: 'text-[#614131]',
      textMuted: 'text-[#876757]',
      accent: 'bg-[#DFB794] text-[#381F13]',
      accentHover: 'hover:bg-[#CF9F75]',
      accentText: 'text-[#D9381E]',
      border: 'border-[#E2DFD7]',
      borderAccent: 'border-[#DFB794]',
      badgeBg: 'bg-[#DFB794]/30',
      badgeText: 'text-[#381F13]',
      radius: 'rounded-3xl',
      shadow: 'shadow-xl shadow-black/10',
      buttonStyle: 'rounded-full px-5 py-2.5 font-black transition-all active:scale-95 shadow-md',
      cardStyle: 'rounded-3xl transition-all duration-300 shadow-sm',
    },
  },

  minimal: {
    id: 'minimal',
    name: 'Minimalist & Clean',
    tagline: 'Estética nórdica de alta precisión, pura y monocromática',
    icon: '🤍',
    badge: 'Scandi Noir',
    isDark: false,
    previewColors: ['#0A0A0A', '#F5F5F5', '#737373', '#E5E5E5'],
    fontFamily: {
      heading: "'Inter', sans-serif",
      body: "'Inter', sans-serif",
    },
    styles: {
      bg: 'bg-[#F8F9FA]',
      bgCard: 'bg-white border-neutral-900',
      bgCardHover: 'hover:border-black hover:shadow-md',
      bgHeader: 'bg-white/95 backdrop-blur-md border-neutral-900',
      textPrimary: 'text-black',
      textSecondary: 'text-neutral-800',
      textMuted: 'text-neutral-600',
      accent: 'bg-black text-white',
      accentHover: 'hover:bg-neutral-800',
      accentText: 'text-black',
      border: 'border-neutral-900',
      borderAccent: 'border-black',
      badgeBg: 'bg-neutral-100 border border-neutral-900',
      badgeText: 'text-black font-extrabold',
      radius: 'rounded-none',
      shadow: 'shadow-none',
      buttonStyle: 'rounded-none uppercase tracking-widest text-xs font-black active:scale-[0.98]',
      cardStyle: 'border-2 border-neutral-900 transition-all',
    },
  },

  luxury: {
    id: 'luxury',
    name: 'Elegante & Haute Café',
    tagline: 'Esmeralda profundo, oro cálido y alta gastronomía',
    icon: '✨',
    badge: 'Luxury Lounge',
    isDark: true,
    previewColors: ['#07140F', '#D4AF37', '#1E3F33', '#FBF8F2'],
    fontFamily: {
      heading: "'Playfair Display', serif",
      body: "'Plus Jakarta Sans', sans-serif",
    },
    styles: {
      bg: 'bg-[#07140F]',
      bgCard: 'bg-[#0F261C] border-[#2A5C47]',
      bgCardHover: 'hover:border-[#D4AF37] hover:shadow-2xl hover:shadow-[#D4AF37]/20',
      bgHeader: 'bg-[#07140F]/95 backdrop-blur-md border-[#2A5C47]',
      textPrimary: 'text-[#FAF7EE]',
      textSecondary: 'text-[#D4E0DA]',
      textMuted: 'text-[#9DB2A8]',
      accent: 'bg-[#D4AF37] text-black font-black',
      accentHover: 'hover:bg-[#E5C358]',
      accentText: 'text-[#E5C358]',
      border: 'border-[#2A5C47]',
      borderAccent: 'border-[#D4AF37]',
      badgeBg: 'bg-[#D4AF37]/20 border border-[#D4AF37]/40',
      badgeText: 'text-[#F3D77B]',
      radius: 'rounded-xl',
      shadow: 'shadow-xl shadow-black/60',
      buttonStyle: 'rounded-lg uppercase tracking-wider font-extrabold text-xs active:scale-95 shadow-lg shadow-[#D4AF37]/25',
      cardStyle: 'border-2 border-[#2A5C47] transition-all duration-300',
    },
  },

  boho: {
    id: 'boho',
    name: 'Boho Chic / Tierra & Sol',
    tagline: 'Arcilla natural, verde salvia y vibra orgánica artesanal',
    icon: '🌿',
    badge: 'Organic & Earth',
    isDark: false,
    previewColors: ['#99583D', '#5E6F52', '#F2E8DC', '#C28D75'],
    fontFamily: {
      heading: "'Syne', sans-serif",
      body: "'Plus Jakarta Sans', sans-serif",
    },
    styles: {
      bg: 'bg-[#F2ECE4]',
      bgCard: 'bg-[#FAF6F0] border-[#C8B8A6]',
      bgCardHover: 'hover:border-[#99583D] hover:shadow-xl hover:shadow-[#99583D]/15',
      bgHeader: 'bg-[#F2ECE4]/95 backdrop-blur-md border-[#C8B8A6]',
      textPrimary: 'text-[#2E1E17]',
      textSecondary: 'text-[#574136]',
      textMuted: 'text-[#7D6457]',
      accent: 'bg-[#99583D] text-white',
      accentHover: 'hover:bg-[#80462F]',
      accentText: 'text-[#99583D]',
      border: 'border-[#C8B8A6]',
      borderAccent: 'border-[#99583D]',
      badgeBg: 'bg-[#5E6F52]/20',
      badgeText: 'text-[#3D4D34] font-extrabold',
      radius: 'rounded-3xl',
      shadow: 'shadow-md shadow-[#99583D]/10',
      buttonStyle: 'rounded-2xl font-extrabold active:scale-95 transition-transform',
      cardStyle: 'border-2 border-[#C8B8A6] transition-all duration-300',
    },
  },

  girly: {
    id: 'girly',
    name: 'Girly Pop & Pastel',
    tagline: 'Fresa dulce, crema, lavanda y burbujas de felicidad',
    icon: '🌸',
    badge: 'Sweet & Aesthetic',
    isDark: false,
    previewColors: ['#FF4D79', '#FFD1DC', '#FFF0F5', '#845EC2'],
    fontFamily: {
      heading: "'DynaPuff', cursive, sans-serif",
      body: "'Plus Jakarta Sans', sans-serif",
    },
    styles: {
      bg: 'bg-[#FFF0F5]',
      bgCard: 'bg-white border-[#FFB6C1]',
      bgCardHover: 'hover:border-[#FF4D79] hover:shadow-xl hover:shadow-[#FF4D79]/25 hover:-translate-y-1',
      bgHeader: 'bg-[#FFF0F5]/95 backdrop-blur-md border-[#FFB6C1]',
      textPrimary: 'text-[#3B1425]',
      textSecondary: 'text-[#6B2D46]',
      textMuted: 'text-[#94526E]',
      accent: 'bg-[#FF4D79] text-white',
      accentHover: 'hover:bg-[#E63963]',
      accentText: 'text-[#FF4D79]',
      border: 'border-[#FFB6C1]',
      borderAccent: 'border-[#FF4D79]',
      badgeBg: 'bg-[#FF4D79]/20 border border-[#FF4D79]/30',
      badgeText: 'text-[#C91A47] font-black',
      radius: 'rounded-3xl',
      shadow: 'shadow-lg shadow-[#FF4D79]/15',
      buttonStyle: 'rounded-full font-black shadow-md shadow-[#FF4D79]/30 active:scale-95 transition-all',
      cardStyle: 'border-2 border-[#FFB6C1] transition-all duration-300',
    },
  },

  comic: {
    id: 'comic',
    name: 'Pop Comic & Retro Art',
    tagline: 'Trazos gruesos, sombras de historieta y energía pop art',
    icon: '🎨',
    badge: 'Comic Pop',
    isDark: false,
    previewColors: ['#FFDE59', '#FF3131', '#000000', '#004AAD'],
    fontFamily: {
      heading: "'Space Grotesk', sans-serif",
      body: "'Space Grotesk', sans-serif",
    },
    styles: {
      bg: 'bg-[#FFFBEB]',
      bgCard: 'bg-white border-3 border-black',
      bgCardHover: 'hover:translate-x-[-3px] hover:translate-y-[-3px] hover:shadow-[6px_6px_0px_0px_rgba(0,0,0,1)]',
      bgHeader: 'bg-[#FFFBEB]/95 backdrop-blur-md border-b-3 border-black',
      textPrimary: 'text-black font-black',
      textSecondary: 'text-neutral-900 font-bold',
      textMuted: 'text-neutral-700 font-semibold',
      accent: 'bg-[#FFDE59] text-black border-2 border-black font-black',
      accentHover: 'hover:bg-[#FDD017]',
      accentText: 'text-black font-black',
      border: 'border-3 border-black',
      borderAccent: 'border-3 border-black',
      badgeBg: 'bg-[#FF3131] text-white font-black border border-black',
      badgeText: 'text-white font-black',
      radius: 'rounded-xl',
      shadow: 'shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]',
      buttonStyle: 'rounded-xl border-2 border-black font-black shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] active:translate-x-[2px] active:translate-y-[2px] active:shadow-none transition-all',
      cardStyle: 'border-3 border-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] transition-all',
    },
  },

  neo: {
    id: 'neo',
    name: 'Neo Cyber Café',
    tagline: 'Modo oscuro OLED, neón cian & ámbar con glassmorphism',
    icon: '⚡',
    badge: 'Cyber Future',
    isDark: true,
    previewColors: ['#060911', '#06B6D4', '#F59E0B', '#1E2E48'],
    fontFamily: {
      heading: "'Space Grotesk', sans-serif",
      body: "'Plus Jakarta Sans', sans-serif",
    },
    styles: {
      bg: 'bg-[#060911]',
      bgCard: 'bg-[#0E1626] border-[#1E2E48]',
      bgCardHover: 'hover:border-[#06B6D4] hover:shadow-2xl hover:shadow-[#06B6D4]/25 hover:-translate-y-1',
      bgHeader: 'bg-[#060911]/95 backdrop-blur-md border-[#1E2E48]',
      textPrimary: 'text-[#FFFFFF]',
      textSecondary: 'text-[#CBD5E1]',
      textMuted: 'text-[#94A3B8]',
      accent: 'bg-[#06B6D4] text-black font-black',
      accentHover: 'hover:bg-[#22D3EE]',
      accentText: 'text-[#22D3EE]',
      border: 'border-[#1E2E48]',
      borderAccent: 'border-[#06B6D4]',
      badgeBg: 'bg-[#06B6D4]/20 border border-[#06B6D4]/40',
      badgeText: 'text-[#22D3EE] font-black',
      radius: 'rounded-2xl',
      shadow: 'shadow-xl shadow-black/80',
      buttonStyle: 'rounded-xl font-black shadow-lg shadow-[#06B6D4]/30 active:scale-95 transition-all',
      cardStyle: 'border-2 border-[#1E2E48] transition-all duration-300',
    },
  },
};
